[profile.default]
src = 'src'
out = 'out'
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
local = "${LOCAL_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
fuji = "${FUJI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
binance = "${BINANCE_RPC_URL}"

[invariant]
runs = 500
depth = 75
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true